### ISSUE TITLE
[mod] request for item/recipe name consitency

### ISSUE THREAD

**Issue by Nexela** [Arch666Angel/angelspetrochems#1]
Totally up to you on this but I was curious if you could rename your barrel items and fill/empty to be consistent

I am playing around with omni barrels and ended up beating my head on a wall till I figured it out:)
updating fill/empty recipes dynamically in data-updates by checking for item then adding fill/empty as a prefix on existing barrel items to update recipes also. This currently breaks with petrochem due to naming.

In base and bob's (and angels thermal water) mod barrels (same for all just using one item for ref)
item.name = NAME-barrel
recipe.name=fill-NAME-barrel
empty.recipe=empty-NAME-barrel

In petrochem
(PS I really like that you put the type of fluid in the name it was the driving factor for modifying omni barrels to use bob's air compressor for gas types :))

item.name = TYPE-NAME-barrel
but Recipe name = ANGELS-FILL-BARREL-TYPE-NAME

So the requested change would be to rename recipes to
fill-TYPE-NAME-barrel (re structuring and dropping angels so it matches)

or rename both items and recipes along the lines of
ANGELS-TYPE-NAME-barrel
and 
fill-ANGELS-TYPE-NAME-barrel

Thanks!

**Comment by Arch666Angel** [comment]
Will reduce the barreling recipes to the raws and add an option to enable barreling recipes for every fluid in my mod.
To your issue: Changed the recipes to this layout
```
    {
    type = "recipe",
    name = "fill-gas-natural-1-barrel",
    category = "crafting-with-fluid",
	subgroup = "angels-barrels",
    energy_required = 0.5,
	enabled = "true",
    ingredients ={
		{type="fluid", name="gas-natural-1", amount=25}
	},
    results=
    {
		{type="item", name="gas-natural-1-barrel", amount=1},
    },
    icon = "__angelspetrochem__/graphics/icons/gas-natural-1.png",
	order = "a[angels-fill-gas-natural-1]",
	},
	{
    type = "recipe",
    name = "empty-gas-natural-1-barrel",
    category = "crafting-with-fluid",
	subgroup = "angels-barrels",
    energy_required = 0.5,
	enabled = "true",
    ingredients ={
		{type="item", name="gas-natural-1-barrel", amount=1},
	},
    results=
    {
		{type="fluid", name="gas-natural-1", amount=25}
    },
    icon = "__angelspetrochem__/graphics/icons/gas-natural-1.png",
	order = "b[angels-empty-gas-natural-1]",
	},
```

**Comment by Nexela** [comment]
Awesome and Thanks!

Can't wait for more PetroChem love!

Noticed in your example though that you are missing the "empty-barrel" in their respective recipe ingredients/results

In case you are interested here are the relevant changes to omnibarrels (which is an awesome mod of course)
https://gist.github.com/Nexela/15baac27863e84cc6abb6ce8295b4ac3
With your changes to recipes I can tidy up the recipe list by just changing certain parts instead of creating new recipes and having possible duplicates with omnibarrel defaults

**Comment by Arch666Angel** [comment]
Yeah that's because I'm considering to add different barrels, or go with the standard barrel from the base game.
